baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'raft'

[menu]
  [[menu.main]]
    url = "/about"
    title = "We are nerdy humans"
    subtitle = "About us and our philosophies"
    class = "nav-arrow-1"
  [[menu.main]]
    url = "/focus-areas"
    title = "doing the work we love"
    subtitle = "Our Focus Areas and Innovation Toolkit"
    class = "nav-arrow-2"
  [[menu.main]]
    url = "/blog"
    title = "+ sharing it with the world."
    subtitle = "Read about Raft’s News + Insights"
    class = "nav-arrow-3"
  [[menu.main]]
    url = "https://boards.greenhouse.io/raft"
    title = "Come *join* the fun."
    subtitle = "Careers at Team Raft"
    class = "nav-arrow-4"
[params]
 [[params.social]]
    
    name = "Twitter"
    icon = "twitter"
    username = "Raft_Tech"
    url = "https://twitter.com/raft_tech"
    desc = "Follow us on Twitter"
    share = true
 [[params.social]]
    name = "GitHub"
    icon = "github"
    username = "raft-tech"
    url = "https://github.com/raft-tech"
    desc = "Fork us on GitHub"
    share = true
 [[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    username = "Raft Tech"
    url = "https://www.linkedin.com/company/raft-tech/"
    desc = "Connect with us on LinkedIn"
    share = true