baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Raft'
theme = 'raft'

paginate = 9

[menu]
[[menu.main]]
  pageRef = '/about'
  name = 'We are nerdy humans'
  weight = 1
  [menu.main.params]
      subtitle = 'About us and our philosophies'
      class = 'nav-arrow-1'
[[menu.main]]
  pageRef = '/focus-areas'
  name = 'doing the work we love'
  weight = 2
  [menu.main.params]
    subtitle = 'Our Focus Areas and Innovation Toolkit'
    class = 'nav-arrow-2'
[[menu.main]]
  pageRef = '/blog'
  name = '\+ sharing it with the world.'
  weight = 3
  [menu.main.params]
    subtitle = 'Read about Raft’s News + Insights'
    class = 'nav-arrow-3'
[[menu.main]]
  pageRef = 'https://boards.greenhouse.io/raft'
  name = 'Come *join* the fun.'
  weight = 4
  [menu.main.params]
    subtitle = 'Careers at Team Raft'
    class = 'nav-arrow-4'

[params]
 phone = '703-570-4820'
 email = 'info@teamraft.com'
 [[params.social]]
    name = 'Twitter'
    icon = 'twitter'
    username = 'Raft_Tech'
    url = 'https://twitter.com/raft_tech'
    desc = 'Follow us on Twitter'
    share = true
 [[params.social]]
    name = 'GitHub'
    icon = 'github'
    username = 'raft-tech'
    url = 'https://github.com/raft-tech'
    desc = 'Fork us on GitHub'
    share = true
 [[params.social]]
    name = 'LinkedIn'
    icon = 'linkedin'
    username = 'Raft Tech'
    url = 'https://www.linkedin.com/company/raft-tech/'
    desc = 'Connect with us on LinkedIn'
    share = true