backend:
  name: github
  repo: raft-tech/raft-tech.github.io # Path to your GitHub repository
  # optional, defaults to main
  branch: hugo
# These lines should *not* be indented
media_folder: /static/images/ # Media files will be stored in the repo under static/images/uploads
public_folder: /images/ # The src attribute for uploaded media will begin with /images/uploads
media_library:
  max_file_size: 512000
  folder_support: true
editor:
  preview: true
  frame: true
  size: half
logo_url: /images/raft-logos/raft-logo.svg
collections:
  - name: home
    label: Home
    files:
      - name: homepage
        label: Homepage
        editor:
          preview: true
          frame: true
          size: half
        file: content/_index.md
        fields: # The fields for each document, usually in front matter
          - label: Title
            name: title
            widget: string
          - label: Draft
            name: draft
            widget: boolean
          - label: Partners
            name: partners
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Logo
                name: logo
                widget: image
    
        
  - name: about
    identifier_field: name
    label: About
    folder: content/about
    create: true
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
  - name: blog
    identifier_field: name
    label: Blog
    folder: content/blog
    create: true
    editor:
      preview: true
      frame: true
      size: half
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: leadership
    label: Leadership
    editor:
      preview: true
      frame: true
      size: half
    files:
      - label: Leaders
        file: data/leadership.yml
        name: leaders
        fields:
          - label: Leaders
            name: leaders
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Role
                name: role
                widget: string
              - label: Song
                name: song
                widget: string
              - label: About
                name: about
                widget: markdown
              - label: Weight
                name: weight
                widget: number